### ISSUE TITLE
IllegalStateException: Cannot play the same instance of a track twice, use track.makeClone().

### ISSUE THREAD

**Issue by ducc** [dabbotorg/java-music-bot#84]
https://sentry.davinci.sh/dabbot/javamusicbot/issues/502/

```
IllegalStateException: Cannot play the same instance of a track twice, use track.makeClone().
    at com.sedmelluq.discord.lavaplayer.track.BaseAudioTrack.assignExecutor(BaseAudioTrack.java:44)
    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.executeTrack(DefaultAudioPlayerManager.java:346)
    at com.sedmelluq.discord.lavaplayer.player.AudioPlayer.startTrack(AudioPlayer.java:119)
    at ovh.not.javamusicbot.TrackScheduler.next(TrackScheduler.java:84)
    at ovh.not.javamusicbot.TrackScheduler.onTrackEnd(TrackScheduler.java:92)
...
(11 additional frame(s) were not displayed)

Handler of event com.sedmelluq.discord.lavaplayer.player.event.TrackEndEvent@57c8ac64 threw an exception.
```

**Comment by ducc** [comment]
don't think this issue still happens but checking on sentry (tehe might have forgotten the password)
